### ISSUE TITLE
Create CSS for qData-related pkgdown websites

### ISSUE THREAD

**Issue by jhollway** [globalgov/panarchic.ch#1]

**Comment by BBieri** [comment]
(Note to self) Check out [this link](https://pkgdown.r-lib.org/reference/init_site.html#custom-css-js)

**Comment by BBieri** [comment]
Note to self: Improve structure in qData of the different functions in the reference function. 

Done !

**Comment by BBieri** [comment]
Closing it for now as CSS was successfully added. Will implement similar CSS when the package websites will become available for other packages in the qVerse
